### ISSUE TITLE
Улучшить поддержку RequireJS

### ISSUE THREAD

**Issue by ekazakov** [code-orchestra/colt-ui#1]
Если изменить объявление модуля, то оно не доедет до браузера.

Пример (https://github.com/ekazakov/RequireJSExample).

```
// ModuleB.js
define(function(require, exports, module) {
    var ModuleA = require("modules/ModuleA");
    var moduleA = new ModuleA("hello ModuleA");
    var z = "some text";

    function ModuleB (b) {
        this.b = b;
    }

    ModuleB.prototype.bar = function() {
        return this.b + " " + moduleA.foo();
    };

    ModuleB.prototype.baz = function() {
        return z;
    };

    module.exports = ModuleB;
});

```

если поменять значение z

`var z = "some new text";`

И в консоле создать новый экземпляр ModuleB

```
var NewModuleB = require("modules/ModuleB");
var newB = new NewModuleB("");
newB.baz();  
```

В результате все равно будет “some text"
Тоже самое с добавлением новых методов в ModuleB.

Хотелось бы, чтобы с обновлением ModuleB.js обновлялись и все его instances.

**Comment by makc** [comment]
тут дело в том, что функция, в которой написано var z = ... не выполняется 2й раз. по идее можно написать как-то так:

``` javascript
define(function(require, exports, module) {
    ...
    var z;

    // @code-update
    function init () {
        z = "some text";
    }
    init();
    ...
```

тогда init выполнится первый раз нормальным образом, а потом будет вызываться при изменениях кода.

**Comment by ekazakov** [comment]
Попробавал ваш вариант. Получил ошибку

```
live method src/modules/ModuleB.js[0]: function(require,exports,module) runtime error: init is not defined
src/modules/~

live method src/index.js[1]: function() runtime error: object is not a function
```

```
start session controller.js:72
stdout: 3 -> 92
Progress: 20% (Copying resources...)   
 services.js:355
stdout: init is not defined
 services.js:355
stdout: pos = 7 (row = 1, column = 487)
 services.js:355
stdout: error maps to: line 7:5
 services.js:355
stdout: validated: line 7:5
 services.js:355
stdout: pos = 155
ReferenceError: init is not defined
    at Object.eval (eval at <anonymous> (http://192.168.1.5:9091/src/modules/ModuleB.js:7:310), <anonymous>:1:487)
    at Object.eval (eval at <anonymous> (http://192.168.1.5:9091/src/modules/ModuleB.js:7:310), <anonymous>:7:163)
    at Object.<anonymous> (http://192.168.1.5:9091/src/modules/ModuleB.js:8:119)
    at Object.eval (eval at <anonymous> (eval at newContext (eval at <anonymous> (http://192.168.1.5:9091/src/components/requirejs/require.js?:112:278))), <anonymous>:1:455)
    at Object.eval (eval at <anonymous> (eval at newContext (eval at <anonymous> (http://192.168.1.5:9091/src/components/requirejs/require.js?:112:278))), <anonymous>:1:476)
    at Object.context.execCb (eval at newContext (eval at <anonymous> (http://192.168.1.5:9091/src/components/requirejs/require.js?:112:278)), <anonymous>:50:302)
    at Object.eval (eval at <anonymous> (eval at newContext (eval at <anonymous> (http://192.168.1.5:9091/src/components/requirejs/require.js?:112:278))), <anonymous>:2:366)
    at Object.eval (eval at <anonymous> (eval at newContext (eval at <anonymous> (http://192.168.1.5:9091/src/components/requirejs/require.js?:112:278))), <anonymous>:4:72)
    at Object.Module.check (eval at newContext (eval at <anonymous> (http://192.168.1.5:9091/src/components/requirejs/require.js?:112:278)), <anonymous>:30:145)
    at Object.eval (eval at <anonymous> (eval at <anonymous> (eval at <anonymous> (eval at newContext (eval at <anonymous> (http://192.168.1.5:9091/src/components/requirejs/require.js?:112:278))))), <anonymous>:1:439)
 services.js:355
stdout: object is not a function
 services.js:355
stdout: pos = 117 (row = 1, column = 352)
 services.js:355
stdout: error maps to: line 6:28
 services.js:355
stdout: validated: line 6:28
pos = 158
TypeError: object is not a function
    at HTMLDocument.eval (eval at <anonymous> (eval at <anonymous> (http://192.168.1.5:9091/src/index.js:4:294)), <anonymous>:1:352)
    at HTMLDocument.eval (eval at <anonymous> (eval at <anonymous> (http://192.168.1.5:9091/src/index.js:4:294)), <anonymous>:1:441)
    at HTMLDocument.eval (eval at <anonymous> (http://192.168.1.5:9091/src/index.js:4:294), <anonymous>:2:333)
    at eval (eval at <anonymous> (eval at <anonymous> (eval at <anonymous> (http://192.168.1.5:9091/src/components/jquery/dist/jquery.js:563:499))), <anonymous>:2:154)
    at eval (eval at <anonymous> (eval at <anonymous> (eval at <anonymous> (http://192.168.1.5:9091/src/components/jquery/dist/jquery.js:563:499))), <anonymous>:2:375)
    at fire (eval at <anonymous> (eval at <anonymous> (http://192.168.1.5:9091/src/components/jquery/dist/jquery.js:563:499)), <anonymous>:3:237)
    at Object.eval (eval at <anonymous> (eval at <anonymous> (eval at <anonymous> (http://192.168.1.5:9091/src/components/jquery/dist/jquery.js:563:499))), <anonymous>:2:6)
    at Object.eval (eval at <anonymous> (eval at <anonymous> (eval at <anonymous> (http://192.168.1.5:9091/src/components/jquery/dist/jquery.js:563:499))), <anonymous>:2:30)
    at Object.self.fireWith [as resolveWith] (eval at <anonymous> (eval at <anonymous> (http://192.168.1.5:9091/src/components/jquery/dist/jquery.js:563:499)), <anonymous>:14:457)
    at Function.eval (eval at <anonymous> (eval at <anonymous> (http://192.168.1.5:9091/src/components/jquery/dist/jquery.js:563:499)), <anonymous>:2:20)

```

**Comment by makc** [comment]
да, это не работает, потому что http://jsfiddle.net/N6vu7/ - я сейчас поправил, чтобы работало так:

``` javascript
// @code-update
    (function () {
        z = "some text";
    })();
```

но надо чтобы кто-то собрал и выложил апдейт. скорее всего сделают в понедельник.

**Comment by makc** [comment]
апдейт для мака уже выложили

**Comment by ekazakov** [comment]
:+1:

**Comment by potapenko** [comment]
сейчас соберем для win/linux
